// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.js";
import * as Zora$1 from "zora";
import * as Table from "../src/Table.js";
import * as TestSetup from "./TestSetup.js";

Zora$1.test("Transactions", (function (t) {
        t.test("Open transaction", (function (t) {
                var dexie = TestSetup.setup(undefined);
                return dexie.transaction("rw", ["friends"], (function (tx) {
                              var friends = tx.table("friends");
                              TestSetup.pt(TestSetup.p(Table.add(friends, {
                                            id: undefined,
                                            name: "Chris",
                                            color: "Red"
                                          }), (function (id) {
                                          return Table.getById(friends, id);
                                        })), (function (result) {
                                      return Zora.optionSome(t, result, (function (t, friend) {
                                                    t.equal(friend.name, "Chris", "Friend should be added in transaction");
                                                    
                                                  }));
                                    }));
                              
                            }));
              }));
        t.test("Abort transaction", (function (t) {
                var dexie = TestSetup.setup(undefined);
                return dexie.transaction("rw", ["friends"], (function (tx) {
                              var friends = tx.table("friends");
                              Table.add(friends, {
                                    id: undefined,
                                    name: "Chris",
                                    color: "Red"
                                  });
                              
                            }));
              }));
        
      }));

export {
  
}
/*  Not a pure module */
