// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import Dexie from "dexie";
import * as Table$Dexie from "../src/Table.mjs";
import * as Version$Dexie from "../src/Version.mjs";

// I couldn't figure out how to do this in Rescript and practicality beats purity
import indexedDB from "fake-indexeddb";
import IDBKeyRange from "fake-indexeddb/lib/FDBKeyRange.js";

Dexie.dependencies.indexedDB = indexedDB;
Dexie.dependencies.IDBKeyRange = IDBKeyRange;
;

var FriendSchema = {
  tableName: "friends"
};

var Friend = Table$Dexie.MakeTable(FriendSchema);

function setup(param) {
  var someNumber = Math.random().toString();
  var dexie = new Dexie("hello dexie " + someNumber + "");
  var schema = [
    [
      "friends",
      "++id,name,birthdate,color"
    ],
    [
      "pets",
      "++id,name,kind"
    ]
  ];
  Version$Dexie.stores(dexie.version(1), schema).upgrade(function (_tx) {
        
      });
  dexie.open();
  return dexie;
}

async function friendFixture(dexie) {
  return await Curry._2(Friend.bulkPut, dexie, [
              {
                id: 1,
                name: "Chris",
                color: "Red"
              },
              {
                id: 2,
                name: "Leroy",
                color: "Blue"
              },
              {
                id: 3,
                name: "Jerome",
                color: "Purple"
              },
              {
                id: 4,
                name: "Betty",
                color: "Purple"
              },
              {
                id: 5,
                name: "Xiao",
                color: "Blue"
              },
              {
                id: 6,
                name: "Rohan",
                color: "Red"
              },
              {
                id: 7,
                name: "Natalia",
                color: "Red"
              },
              {
                id: 8,
                name: "Padma",
                color: "Purple"
              }
            ]);
}

export {
  FriendSchema ,
  Friend ,
  setup ,
  friendFixture ,
}
/*  Not a pure module */
