// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.js";
import Dexie from "dexie";
import FDBFactoryJs from "fake-indexeddb/lib/FDBFactory.js";
import FDBKeyRangeJs from "fake-indexeddb/lib/FDBKeyRange.js";

function $$default(t) {
  t.test("factory makes two instances", (function (t) {
          var idb = new FDBFactoryJs();
          var dexie = new Dexie("hello dexie", {
                indexedDB: idb,
                IDBKeyRange: FDBKeyRangeJs
              });
          console.log(dexie);
          t.ok(true, "It is fine");
          return Zora.done(undefined);
        }));
  
}

export {
  $$default ,
  $$default as default,
  
}
/* dexie Not a pure module */
