// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as Table from "../node_modules/@dusty-phillips/rescript-dexie/src/Table.mjs";
import Dexie from "dexie";
import * as React from "react";
import * as Caml_option from "../node_modules/rescript/lib/es6/caml_option.js";
import * as DexieVersion from "../node_modules/@dusty-phillips/rescript-dexie/src/DexieVersion.mjs";
import * as DexieReactHooks from "dexie-react-hooks";

function Demo$Counter(Props) {
  var dexie = Props.dexie;
  var countOption = DexieReactHooks.useLiveQuery(function (param) {
        return Table.getById(dexie.table("count"), 1);
      });
  if (countOption === undefined) {
    return React.createElement("div", undefined, " No count ");
  }
  var count = Caml_option.valFromOption(countOption);
  return React.createElement("div", undefined, React.createElement("div", undefined, "Counter is " + count.count.toString()), React.createElement("button", {
                  onClick: (function (param) {
                      console.log(count);
                      Table.put(dexie.table("count"), {
                            id: 1,
                            count: count.count + 1 | 0
                          });
                      
                    })
                }, "Count"));
}

var Counter = {
  make: Demo$Counter
};

function Demo(Props) {
  var match = React.useState(function () {
        
      });
  var setDexie = match[1];
  var dexieOption = match[0];
  React.useEffect((function () {
          var dexie = new Dexie("Example");
          var schema = [[
              "count",
              "++id"
            ]];
          DexieVersion.stores(dexie.version(1), schema);
          Curry._1(setDexie, (function (_prev) {
                  return Caml_option.some(dexie);
                }));
          
        }), []);
  if (dexieOption !== undefined) {
    return React.createElement(Demo$Counter, {
                dexie: Caml_option.valFromOption(dexieOption)
              });
  } else {
    return React.createElement("div", undefined, "Hello World");
  }
}

var make = Demo;

export {
  Counter ,
  make ,
  
}
/* dexie Not a pure module */
