// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import Dexie from "dexie";
import * as React from "react";
import * as Caml_option from "../node_modules/rescript/lib/es6/caml_option.js";
import * as Table$Dexie from "../node_modules/@dusty-phillips/rescript-dexie/src/Table.mjs";
import * as Version$Dexie from "../node_modules/@dusty-phillips/rescript-dexie/src/Version.mjs";
import * as DexieReactHooks from "dexie-react-hooks";

var CountSchema = {
  tableName: "count"
};

var Count = Table$Dexie.MakeTable(CountSchema);

function Demo$Counter(Props) {
  var dexie = Props.dexie;
  var countOption = DexieReactHooks.useLiveQuery(function (param) {
        return Curry._2(Count.getById, dexie, 1);
      });
  if (countOption !== undefined) {
    return React.createElement("div", undefined, React.createElement("div", undefined, "Counter is " + countOption.count.toString()), React.createElement("button", {
                    onClick: (function (param) {
                        Curry._2(Count.put, dexie, {
                              id: 1,
                              count: countOption.count + 1 | 0
                            });
                        
                      })
                  }, "Count"));
  } else {
    return React.createElement("div", undefined, React.createElement("button", {
                    onClick: (function (param) {
                        Curry._2(Count.put, dexie, {
                              id: 1,
                              count: 1
                            });
                        
                      })
                  }, "Count"), React.createElement("div", undefined, " No count "));
  }
}

var Counter = {
  make: Demo$Counter
};

function Demo(Props) {
  var match = React.useState(function () {
        
      });
  var setDexie = match[1];
  var dexieOption = match[0];
  React.useEffect((function () {
          var dexie = new Dexie("Example");
          var schema = [[
              "count",
              "++id"
            ]];
          Version$Dexie.stores(dexie.version(1), schema);
          Curry._1(setDexie, (function (_prev) {
                  return Caml_option.some(dexie);
                }));
          
        }), []);
  if (dexieOption !== undefined) {
    return React.createElement(Demo$Counter, {
                dexie: Caml_option.valFromOption(dexieOption)
              });
  } else {
    return React.createElement("div", undefined, "Hello World");
  }
}

var make = Demo;

export {
  CountSchema ,
  Count ,
  Counter ,
  make ,
  
}
/* Count Not a pure module */
