// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function MakeTable(Schema) {
  var add = function (id, dexie, item) {
    if (id !== undefined) {
      return dexie.table(Schema.tableName).add(item, Caml_option.valFromOption(id));
    } else {
      return dexie.table(Schema.tableName).add(item);
    }
  };
  var bulkAdd = function (dexie, items) {
    return dexie.table(Schema.tableName).bulkAdd(items, {
                allKeys: true
              });
  };
  var bulkPut = function (dexie, items) {
    return dexie.table(Schema.tableName).bulkPut(items, {
                allKeys: true
              });
  };
  var bulkDelete = function (dexie, items) {
    return dexie.table(Schema.tableName).bulkDelete(items);
  };
  var bulkGet = function (dexie, ids) {
    return dexie.table(Schema.tableName).bulkGet(ids);
  };
  var count = function (dexie) {
    return dexie.table(Schema.tableName).count();
  };
  var $$delete = function (dexie, id) {
    return dexie.table(Schema.tableName).delete(id);
  };
  var findByCriteria = function (dexie, criteria) {
    return dexie.table(Schema.tableName).where(criteria);
  };
  var getById = function (dexie, id) {
    return dexie.table(Schema.tableName).get(id);
  };
  var getByCriteria = function (dexie, criteria) {
    return dexie.table(Schema.tableName).get(criteria);
  };
  var put = function (id, dexie, item) {
    if (id !== undefined) {
      return dexie.table(Schema.tableName).put(item, Caml_option.valFromOption(id));
    } else {
      return dexie.table(Schema.tableName).put(item);
    }
  };
  var update = function (dexie, id, patch) {
    return dexie.table(Schema.tableName).update(id, patch);
  };
  var where = function (dexie, fieldName) {
    return dexie.table(Schema.tableName).where(fieldName);
  };
  var toArray = function (dexie) {
    return dexie.table(Schema.tableName).toArray();
  };
  var toCollection = function (dexie) {
    return dexie.table(Schema.tableName).toCollection();
  };
  return {
          add: add,
          bulkAdd: bulkAdd,
          bulkPut: bulkPut,
          bulkDelete: bulkDelete,
          bulkGet: bulkGet,
          count: count,
          $$delete: $$delete,
          findByCriteria: findByCriteria,
          getById: getById,
          getByCriteria: getByCriteria,
          put: put,
          update: update,
          where: where,
          toArray: toArray,
          toCollection: toCollection
        };
}

export {
  MakeTable ,
}
/* No side effect */
