// Generated by ReScript, PLEASE EDIT WITH CARE


function bulkAdd(table, items) {
  return table.bulkAdd(items, {
              allKeys: true
            });
}

function bulkPut(table, items) {
  return table.bulkPut(items, {
              allKeys: true
            });
}

function add(prim0, prim1) {
  return prim0.add(prim1);
}

function bulkGet(prim0, prim1) {
  return prim0.bulkGet(prim1);
}

function bulkDelete(prim0, prim1) {
  return prim0.bulkDelete(prim1);
}

function count(prim) {
  return prim.count();
}

function $$delete(prim0, prim1) {
  return prim0.delete(prim1);
}

function findeByCriteria(prim0, prim1) {
  return prim0.where(prim1);
}

function getById(prim0, prim1) {
  return prim0.get(prim1);
}

function getByCriteria(prim0, prim1) {
  return prim0.get(prim1);
}

function put(prim0, prim1) {
  return prim0.put(prim1);
}

function update(prim0, prim1, prim2) {
  return prim0.update(prim1, prim2);
}

export {
  add ,
  bulkAdd ,
  bulkGet ,
  bulkPut ,
  bulkDelete ,
  count ,
  $$delete ,
  findeByCriteria ,
  getById ,
  getByCriteria ,
  put ,
  update ,
  
}
/* No side effect */
