// Generated by ReScript, PLEASE EDIT WITH CARE


function MakeTable(Schema) {
  var bulkAdd = function (table, items) {
    return table.bulkAdd(items, {
                allKeys: true
              });
  };
  var bulkPut = function (table, items) {
    return table.bulkPut(items, {
                allKeys: true
              });
  };
  var table = function (database) {
    return database.table(Schema.tableName);
  };
  return {
          bulkAdd: bulkAdd,
          bulkPut: bulkPut,
          table: table
        };
}

export {
  MakeTable ,
  
}
/* No side effect */
