// Generated by ReScript, PLEASE EDIT WITH CARE


function bulkAdd(table, items) {
  return table.bulkAdd(items, {
              allKeys: true
            });
}

function add(prim0, prim1) {
  return prim0.add(prim1);
}

function bulkDelete(prim0, prim1) {
  return prim0.bulkDelete(prim1);
}

function count(prim) {
  return prim.count();
}

function $$delete(prim0, prim1) {
  return prim0.delete(prim1);
}

function getById(prim0, prim1) {
  return prim0.get(prim1);
}

function getByCriteria(prim0, prim1) {
  return prim0.get(prim1);
}

function put(prim0, prim1) {
  return prim0.put(prim1);
}

export {
  add ,
  bulkAdd ,
  bulkDelete ,
  count ,
  $$delete ,
  getById ,
  getByCriteria ,
  put ,
  
}
/* No side effect */
